DRILLING_RIG_RORATY_SPEED = 90
DRILLING_RIG_HOOK_LOAD = 169
DRILLING_RIG_MUD_PRESSURE = 30
DRILLING_RIG_DRILLING_LINE_HOIST_SPEED = 26

DRILLING_BIT_TEMPERATURE = 0
DRILLING_BIT_VIBRATION_LEVEL = 25
DRILLING_BIT_MUD_PRESSURE = 20

DRILLING_MUD_TEMPERATURE = 50
DRILLING_MUD_GAS_CUT = 3
DRILLING_MUD_PRESSURE = 23
DRILLING_MUD_DENSITY = 1.3
DRILLING_MUD_SPEED = 43
DRILLING_MUD_MAX_LEVEL = 70  # in percentage
DRILLING_MUD_MIN_LEVEL = 30  # in percentage

PREVENTER_EQUIPMENT_TEMPERATURE = 24
PREVENTER_VIBRATION_LEVEL = 9
PREVENTER_MUD_TEMPERATURE = 47
PREVENTER_FLOW_RATE = 44
PREVENTER_LEVEL = 3
PREVENTER_LEAK_LEVEL = 2
PREVENTER_PRESSURE = 23
