DRILLING_RIG_RORATY_SPEED = 90
DRILLING_RIG_RORATY_SPEED_MIN = 80
DRILLING_RIG_RORATY_SPEED_MAX = 150

DRILLING_RIG_HOOK_LOAD = 169
DRILLING_RIG_HOOK_LOAD_MIN = 150
DRILLING_RIG_HOOK_LOAD_MAX = 300

DRILLING_RIG_MUD_PRESSURE = 25
DRILLING_RIG_MUD_PRESSURE_MIN = 10
DRILLING_RIG_MUD_PRESSURE_MAX = 30

DRILLING_RIG_DRILLING_LINE_HOIST_SPEED = 26

DRILLING_BIT_TEMPERATURE = 0

DRILLING_BIT_VIBRATION_LEVEL = 25
DRILLING_BIT_VIBRATION_LEVEL_MIN = 10
DRILLING_BIT_VIBRATION_LEVEL_MAX = 30

DRILLING_BIT_MUD_PRESSURE = 20
DRILLING_BIT_MUD_PRESSURE_MIN = 10
DRILLING_BIT_MUD_PRESSURE_MAX = 40

DRILLING_MUD_TEMPERATURE = 56
DRILLING_MUD_TEMPERATURE_MIN = 50
DRILLING_MUD_TEMPERATURE_MAX = 80

DRILLING_MUD_GAS_CUT = 2
DRILLING_MUD_GAS_CUT_MIN = 0
DRILLING_MUD_GAS_CUT_MIN = 3

DRILLING_MUD_PRESSURE = 23
DRILLING_MUD_PRESSURE_MIN = 10
DRILLING_MUD_PRESSURE_MAX = 30

DRILLING_MUD_DENSITY = 12

DRILLING_MUD_SPEED = 43
DRILLING_MUD_SPEED_MIN = 30
DRILLING_MUD_SPEED_MAX = 50

DRILLING_MUD_MAX_LEVEL = 70  # in percentage
DRILLING_MUD_MIN_LEVEL = 30  # in percentage

PREVENTER_EQUIPMENT_TEMPERATURE = 30
PREVENTER_EQUIPMENT_TEMPERATURE_MIN = 25
PREVENTER_EQUIPMENT_TEMPERATURE_MAX = 60

PREVENTER_VIBRATION_LEVEL = 9

PREVENTER_MUD_TEMPERATURE = 47
PREVENTER_MUD_TEMPERATURE_MIN = 30
PREVENTER_MUD_TEMPERATURE_MAX = 80

PREVENTER_FLOW_RATE = 44
PREVENTER_FLOW_RATE_MIN = 30
PREVENTER_FLOW_RATE_MAX = 50

PREVENTED_GAS_CUT = 1
PREVENTED_GAS_CUT_MIN = 0
PREVENTED_GAS_CUT_MAX = 3

PREVENTER_LEAK_LEVEL = 2
PREVENTER_LEAK_LEVEL_MIN = 0
PREVENTER_LEAK_LEVEL_MAX = 4

PREVENTER_PRESSURE = 23
PREVENTER_PRESSURE_MIN = 10
PREVENTER_PRESSURE_MAX = 30

DRAWWORK_INCLINATION_MIN = 0
DRAWWORK_INCLINATION_MAX = 14

DRAWWORK_TENSION_MIN = 50
DRAWWORK_TENSION_MAX = 400

DRAWWORK_VIBRATION_MIN = 10
DRAWWORK_VIBRATION_MAX = 30
